/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppPreviewRouteImport } from './routes/app-preview'
import { Route as JoinRouteImport } from './routes/join'
import { Route as ReportSiteRouteImport } from './routes/report-site'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DotwellKnownAppleAppSiteAssociationRouteImport } from './routes/[.]well-known/apple-app-site-association'
import { Route as DotwellKnownJwksDotjsonRouteImport } from './routes/[.]well-known/jwks[.]json'
import { Route as DownloadLinuxRouteImport } from './routes/download/linux'
import { Route as DownloadMacosRouteImport } from './routes/download/macos'
import { Route as DownloadWindowsRouteImport } from './routes/download/windows'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as GuidesSlugRouteImport } from './routes/guides/$slug'
import { Route as GuidesRssDotxmlRouteImport } from './routes/guides/rss[.]xml'
import { Route as HealthLiveRouteImport } from './routes/health/live'
import { Route as HealthReadyRouteImport } from './routes/health/ready'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as NewsSlugRouteImport } from './routes/news/$slug'
import { Route as NewsRssDotxmlRouteImport } from './routes/news/rss[.]xml'
import { Route as PluginsIndexRouteImport } from './routes/plugins/index'
import { Route as PluginsSlugRouteImport } from './routes/plugins/$slug'
import { Route as V1MeRouteImport } from './routes/v1/me'
import { Route as PluginsIconSlugRouteImport } from './routes/plugins/icon/$slug'
import { Route as V1AuthLogoutRouteImport } from './routes/v1/auth/logout'
import { Route as V1AvatarsUserIdRouteImport } from './routes/v1/avatars/$userId'
import { Route as V1MeAvatarRouteImport } from './routes/v1/me/avatar'
import { Route as V1MeProfileRouteImport } from './routes/v1/me/profile'
import { Route as V1MobileAuthDevicesRouteImport } from './routes/v1/mobile-auth/devices'
import { Route as V1MobileAuthRedeemRouteImport } from './routes/v1/mobile-auth/redeem'
import { Route as V1MobileAuthSessionRouteImport } from './routes/v1/mobile-auth/session'
import { Route as V1MobileAuthTicketRouteImport } from './routes/v1/mobile-auth/ticket'
import { Route as V1SitesIndexRouteImport } from './routes/v1/sites/index'
import { Route as V1SitesSiteIdRouteImport } from './routes/v1/sites/$siteId'
import { Route as V1SitesReportsRouteImport } from './routes/v1/sites/reports'
import { Route as V1SkillsIndexRouteImport } from './routes/v1/skills/index'
import { Route as V1SkillsSkillIdRouteImport } from './routes/v1/skills/$skillId'
import { Route as V1SkillsMineRouteImport } from './routes/v1/skills/mine'
import { Route as V1TeamAuthRedeemRouteImport } from './routes/v1/team-auth/redeem'
import { Route as V1TeamAuthTicketRouteImport } from './routes/v1/team-auth/ticket'
import { Route as V1TeamHostsIceServersRouteImport } from './routes/v1/team-hosts/ice-servers'
import { Route as V1TeamInvitationsEmailRouteImport } from './routes/v1/team-invitations/email'
import { Route as V1TeamTunnelsProvisionRouteImport } from './routes/v1/team-tunnels/provision'
import { Route as V1AuthEmailStartRouteImport } from './routes/v1/auth/email/start'
import { Route as V1AuthEmailVerifyRouteImport } from './routes/v1/auth/email/verify'
import { Route as V1MarketplaceAgentsIndexRouteImport } from './routes/v1/marketplace/agents/index'
import { Route as V1MarketplaceAgentsAgentIdRouteImport } from './routes/v1/marketplace/agents/$agentId'
import { Route as V1MarketplaceAgentsMineRouteImport } from './routes/v1/marketplace/agents/mine'
import { Route as V1MobileAuthDevicesSessionIdRouteImport } from './routes/v1/mobile-auth/devices/$sessionId'
import { Route as V1SkillsSkillIdContentRouteImport } from './routes/v1/skills/$skillId/content'
import { Route as V1SkillsSkillIdIconRouteImport } from './routes/v1/skills/$skillId/icon'
import { Route as V1SkillsSkillIdInstallRouteImport } from './routes/v1/skills/$skillId/install'
import { Route as V1SkillsAdminSubmissionsRouteImport } from './routes/v1/skills/admin/submissions'
import { Route as V2RemoteHostsIndexRouteImport } from './routes/v2/remote/hosts/index'
import { Route as V2RemoteHostsRegisterRouteImport } from './routes/v2/remote/hosts/register'
import { Route as V2RemoteInvitesInviteIdRouteImport } from './routes/v2/remote/invites/$inviteId'
import { Route as V2RemoteInvitesAcceptRouteImport } from './routes/v2/remote/invites/accept'
import { Route as V2RemoteInvitesPreviewRouteImport } from './routes/v2/remote/invites/preview'
import { Route as V2RemoteResumeValidateRouteImport } from './routes/v2/remote/resume/validate'
import { Route as V2RemoteSessionsIndexRouteImport } from './routes/v2/remote/sessions/index'
import { Route as V1MarketplaceAgentsAgentIdAvatarRouteImport } from './routes/v1/marketplace/agents/$agentId/avatar'
import { Route as V1MarketplaceAgentsAgentIdInstallRouteImport } from './routes/v1/marketplace/agents/$agentId/install'
import { Route as V1MarketplaceAgentsAdminSubmissionsRouteImport } from './routes/v1/marketplace/agents/admin/submissions'
import { Route as V1SitesAdminSiteIdBlockRouteImport } from './routes/v1/sites/admin/$siteId/block'
import { Route as V1SitesUploadsUploadIdActivateRouteImport } from './routes/v1/sites/uploads/$uploadId/activate'
import { Route as V1SitesUploadsUploadIdFileRouteImport } from './routes/v1/sites/uploads/$uploadId/file'
import { Route as V1SkillsSkillIdVersionsVersionIdRouteImport } from './routes/v1/skills/$skillId/versions/$versionId'
import { Route as V1SkillsAdminFeaturedSkillIdRouteImport } from './routes/v1/skills/admin/featured/$skillId'
import { Route as V1SkillsAdminSubmissionsVersionIdRouteImport } from './routes/v1/skills/admin/submissions/$versionId'
import { Route as V2RemoteHostsHostIdInvitesRouteImport } from './routes/v2/remote/hosts/$hostId/invites'
import { Route as V2RemoteHostsHostIdLogoRouteImport } from './routes/v2/remote/hosts/$hostId/logo'
import { Route as V2RemoteHostsHostIdTicketRouteImport } from './routes/v2/remote/hosts/$hostId/ticket'
import { Route as V2RemoteSessionsSessionIdEndRouteImport } from './routes/v2/remote/sessions/$sessionId/end'
import { Route as V2RemoteSessionsSessionIdTicketRouteImport } from './routes/v2/remote/sessions/$sessionId/ticket'
import { Route as V1MarketplaceAgentsAdminFeaturedAgentIdRouteImport } from './routes/v1/marketplace/agents/admin/featured/$agentId'
import { Route as V1MarketplaceAgentsAdminSubmissionsVersionIdRouteImport } from './routes/v1/marketplace/agents/admin/submissions/$versionId'
import { Route as V1SkillsSkillIdVersionsVersionIdContentRouteImport } from './routes/v1/skills/$skillId/versions/$versionId/content'
import { Route as V2RemoteHostsHostIdMembersIndexRouteImport } from './routes/v2/remote/hosts/$hostId/members/index'
import { Route as V2RemoteHostsHostIdMembersMembershipIdRouteImport } from './routes/v2/remote/hosts/$hostId/members/$membershipId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPreviewRoute = AppPreviewRouteImport.update({
  id: '/app-preview',
  path: '/app-preview',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/app-preview.lazy').then((d) => d.Route))
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportSiteRoute = ReportSiteRouteImport.update({
  id: '/report-site',
  path: '/report-site',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownAppleAppSiteAssociationRoute =
  DotwellKnownAppleAppSiteAssociationRouteImport.update({
    id: '/.well-known/apple-app-site-association',
    path: '/.well-known/apple-app-site-association',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownJwksDotjsonRoute = DotwellKnownJwksDotjsonRouteImport.update({
  id: '/.well-known/jwks.json',
  path: '/.well-known/jwks.json',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadLinuxRoute = DownloadLinuxRouteImport.update({
  id: '/download/linux',
  path: '/download/linux',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadMacosRoute = DownloadMacosRouteImport.update({
  id: '/download/macos',
  path: '/download/macos',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadWindowsRoute = DownloadWindowsRouteImport.update({
  id: '/download/windows',
  path: '/download/windows',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRssDotxmlRoute = GuidesRssDotxmlRouteImport.update({
  id: '/guides/rss.xml',
  path: '/guides/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthLiveRoute = HealthLiveRouteImport.update({
  id: '/health/live',
  path: '/health/live',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthReadyRoute = HealthReadyRouteImport.update({
  id: '/health/ready',
  path: '/health/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRssDotxmlRoute = NewsRssDotxmlRouteImport.update({
  id: '/news/rss.xml',
  path: '/news/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsIndexRoute = PluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsSlugRoute = PluginsSlugRouteImport.update({
  id: '/plugins/$slug',
  path: '/plugins/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const V1MeRoute = V1MeRouteImport.update({
  id: '/v1/me',
  path: '/v1/me',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsIconSlugRoute = PluginsIconSlugRouteImport.update({
  id: '/plugins/icon/$slug',
  path: '/plugins/icon/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const V1AuthLogoutRoute = V1AuthLogoutRouteImport.update({
  id: '/v1/auth/logout',
  path: '/v1/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const V1AvatarsUserIdRoute = V1AvatarsUserIdRouteImport.update({
  id: '/v1/avatars/$userId',
  path: '/v1/avatars/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const V1MeAvatarRoute = V1MeAvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => V1MeRoute,
} as any)
const V1MeProfileRoute = V1MeProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => V1MeRoute,
} as any)
const V1MobileAuthDevicesRoute = V1MobileAuthDevicesRouteImport.update({
  id: '/v1/mobile-auth/devices',
  path: '/v1/mobile-auth/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const V1MobileAuthRedeemRoute = V1MobileAuthRedeemRouteImport.update({
  id: '/v1/mobile-auth/redeem',
  path: '/v1/mobile-auth/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const V1MobileAuthSessionRoute = V1MobileAuthSessionRouteImport.update({
  id: '/v1/mobile-auth/session',
  path: '/v1/mobile-auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const V1MobileAuthTicketRoute = V1MobileAuthTicketRouteImport.update({
  id: '/v1/mobile-auth/ticket',
  path: '/v1/mobile-auth/ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const V1SitesIndexRoute = V1SitesIndexRouteImport.update({
  id: '/v1/sites/',
  path: '/v1/sites/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1SitesSiteIdRoute = V1SitesSiteIdRouteImport.update({
  id: '/v1/sites/$siteId',
  path: '/v1/sites/$siteId',
  getParentRoute: () => rootRouteImport,
} as any)
const V1SitesReportsRoute = V1SitesReportsRouteImport.update({
  id: '/v1/sites/reports',
  path: '/v1/sites/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const V1SkillsIndexRoute = V1SkillsIndexRouteImport.update({
  id: '/v1/skills/',
  path: '/v1/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1SkillsSkillIdRoute = V1SkillsSkillIdRouteImport.update({
  id: '/v1/skills/$skillId',
  path: '/v1/skills/$skillId',
  getParentRoute: () => rootRouteImport,
} as any)
const V1SkillsMineRoute = V1SkillsMineRouteImport.update({
  id: '/v1/skills/mine',
  path: '/v1/skills/mine',
  getParentRoute: () => rootRouteImport,
} as any)
const V1TeamAuthRedeemRoute = V1TeamAuthRedeemRouteImport.update({
  id: '/v1/team-auth/redeem',
  path: '/v1/team-auth/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const V1TeamAuthTicketRoute = V1TeamAuthTicketRouteImport.update({
  id: '/v1/team-auth/ticket',
  path: '/v1/team-auth/ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const V1TeamHostsIceServersRoute = V1TeamHostsIceServersRouteImport.update({
  id: '/v1/team-hosts/ice-servers',
  path: '/v1/team-hosts/ice-servers',
  getParentRoute: () => rootRouteImport,
} as any)
const V1TeamInvitationsEmailRoute = V1TeamInvitationsEmailRouteImport.update({
  id: '/v1/team-invitations/email',
  path: '/v1/team-invitations/email',
  getParentRoute: () => rootRouteImport,
} as any)
const V1TeamTunnelsProvisionRoute = V1TeamTunnelsProvisionRouteImport.update({
  id: '/v1/team-tunnels/provision',
  path: '/v1/team-tunnels/provision',
  getParentRoute: () => rootRouteImport,
} as any)
const V1AuthEmailStartRoute = V1AuthEmailStartRouteImport.update({
  id: '/v1/auth/email/start',
  path: '/v1/auth/email/start',
  getParentRoute: () => rootRouteImport,
} as any)
const V1AuthEmailVerifyRoute = V1AuthEmailVerifyRouteImport.update({
  id: '/v1/auth/email/verify',
  path: '/v1/auth/email/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const V1MarketplaceAgentsIndexRoute =
  V1MarketplaceAgentsIndexRouteImport.update({
    id: '/v1/marketplace/agents/',
    path: '/v1/marketplace/agents/',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1MarketplaceAgentsAgentIdRoute =
  V1MarketplaceAgentsAgentIdRouteImport.update({
    id: '/v1/marketplace/agents/$agentId',
    path: '/v1/marketplace/agents/$agentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1MarketplaceAgentsMineRoute = V1MarketplaceAgentsMineRouteImport.update({
  id: '/v1/marketplace/agents/mine',
  path: '/v1/marketplace/agents/mine',
  getParentRoute: () => rootRouteImport,
} as any)
const V1MobileAuthDevicesSessionIdRoute =
  V1MobileAuthDevicesSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => V1MobileAuthDevicesRoute,
  } as any)
const V1SkillsSkillIdContentRoute = V1SkillsSkillIdContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => V1SkillsSkillIdRoute,
} as any)
const V1SkillsSkillIdIconRoute = V1SkillsSkillIdIconRouteImport.update({
  id: '/icon',
  path: '/icon',
  getParentRoute: () => V1SkillsSkillIdRoute,
} as any)
const V1SkillsSkillIdInstallRoute = V1SkillsSkillIdInstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => V1SkillsSkillIdRoute,
} as any)
const V1SkillsAdminSubmissionsRoute =
  V1SkillsAdminSubmissionsRouteImport.update({
    id: '/v1/skills/admin/submissions',
    path: '/v1/skills/admin/submissions',
    getParentRoute: () => rootRouteImport,
  } as any)
const V2RemoteHostsIndexRoute = V2RemoteHostsIndexRouteImport.update({
  id: '/v2/remote/hosts/',
  path: '/v2/remote/hosts/',
  getParentRoute: () => rootRouteImport,
} as any)
const V2RemoteHostsRegisterRoute = V2RemoteHostsRegisterRouteImport.update({
  id: '/v2/remote/hosts/register',
  path: '/v2/remote/hosts/register',
  getParentRoute: () => rootRouteImport,
} as any)
const V2RemoteInvitesInviteIdRoute = V2RemoteInvitesInviteIdRouteImport.update({
  id: '/v2/remote/invites/$inviteId',
  path: '/v2/remote/invites/$inviteId',
  getParentRoute: () => rootRouteImport,
} as any)
const V2RemoteInvitesAcceptRoute = V2RemoteInvitesAcceptRouteImport.update({
  id: '/v2/remote/invites/accept',
  path: '/v2/remote/invites/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const V2RemoteInvitesPreviewRoute = V2RemoteInvitesPreviewRouteImport.update({
  id: '/v2/remote/invites/preview',
  path: '/v2/remote/invites/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const V2RemoteResumeValidateRoute = V2RemoteResumeValidateRouteImport.update({
  id: '/v2/remote/resume/validate',
  path: '/v2/remote/resume/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const V2RemoteSessionsIndexRoute = V2RemoteSessionsIndexRouteImport.update({
  id: '/v2/remote/sessions/',
  path: '/v2/remote/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1MarketplaceAgentsAgentIdAvatarRoute =
  V1MarketplaceAgentsAgentIdAvatarRouteImport.update({
    id: '/avatar',
    path: '/avatar',
    getParentRoute: () => V1MarketplaceAgentsAgentIdRoute,
  } as any)
const V1MarketplaceAgentsAgentIdInstallRoute =
  V1MarketplaceAgentsAgentIdInstallRouteImport.update({
    id: '/install',
    path: '/install',
    getParentRoute: () => V1MarketplaceAgentsAgentIdRoute,
  } as any)
const V1MarketplaceAgentsAdminSubmissionsRoute =
  V1MarketplaceAgentsAdminSubmissionsRouteImport.update({
    id: '/v1/marketplace/agents/admin/submissions',
    path: '/v1/marketplace/agents/admin/submissions',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1SitesAdminSiteIdBlockRoute = V1SitesAdminSiteIdBlockRouteImport.update({
  id: '/v1/sites/admin/$siteId/block',
  path: '/v1/sites/admin/$siteId/block',
  getParentRoute: () => rootRouteImport,
} as any)
const V1SitesUploadsUploadIdActivateRoute =
  V1SitesUploadsUploadIdActivateRouteImport.update({
    id: '/v1/sites/uploads/$uploadId/activate',
    path: '/v1/sites/uploads/$uploadId/activate',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1SitesUploadsUploadIdFileRoute =
  V1SitesUploadsUploadIdFileRouteImport.update({
    id: '/v1/sites/uploads/$uploadId/file',
    path: '/v1/sites/uploads/$uploadId/file',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1SkillsSkillIdVersionsVersionIdRoute =
  V1SkillsSkillIdVersionsVersionIdRouteImport.update({
    id: '/versions/$versionId',
    path: '/versions/$versionId',
    getParentRoute: () => V1SkillsSkillIdRoute,
  } as any)
const V1SkillsAdminFeaturedSkillIdRoute =
  V1SkillsAdminFeaturedSkillIdRouteImport.update({
    id: '/v1/skills/admin/featured/$skillId',
    path: '/v1/skills/admin/featured/$skillId',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1SkillsAdminSubmissionsVersionIdRoute =
  V1SkillsAdminSubmissionsVersionIdRouteImport.update({
    id: '/$versionId',
    path: '/$versionId',
    getParentRoute: () => V1SkillsAdminSubmissionsRoute,
  } as any)
const V2RemoteHostsHostIdInvitesRoute =
  V2RemoteHostsHostIdInvitesRouteImport.update({
    id: '/v2/remote/hosts/$hostId/invites',
    path: '/v2/remote/hosts/$hostId/invites',
    getParentRoute: () => rootRouteImport,
  } as any)
const V2RemoteHostsHostIdLogoRoute = V2RemoteHostsHostIdLogoRouteImport.update({
  id: '/v2/remote/hosts/$hostId/logo',
  path: '/v2/remote/hosts/$hostId/logo',
  getParentRoute: () => rootRouteImport,
} as any)
const V2RemoteHostsHostIdTicketRoute =
  V2RemoteHostsHostIdTicketRouteImport.update({
    id: '/v2/remote/hosts/$hostId/ticket',
    path: '/v2/remote/hosts/$hostId/ticket',
    getParentRoute: () => rootRouteImport,
  } as any)
const V2RemoteSessionsSessionIdEndRoute =
  V2RemoteSessionsSessionIdEndRouteImport.update({
    id: '/v2/remote/sessions/$sessionId/end',
    path: '/v2/remote/sessions/$sessionId/end',
    getParentRoute: () => rootRouteImport,
  } as any)
const V2RemoteSessionsSessionIdTicketRoute =
  V2RemoteSessionsSessionIdTicketRouteImport.update({
    id: '/v2/remote/sessions/$sessionId/ticket',
    path: '/v2/remote/sessions/$sessionId/ticket',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1MarketplaceAgentsAdminFeaturedAgentIdRoute =
  V1MarketplaceAgentsAdminFeaturedAgentIdRouteImport.update({
    id: '/v1/marketplace/agents/admin/featured/$agentId',
    path: '/v1/marketplace/agents/admin/featured/$agentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1MarketplaceAgentsAdminSubmissionsVersionIdRoute =
  V1MarketplaceAgentsAdminSubmissionsVersionIdRouteImport.update({
    id: '/$versionId',
    path: '/$versionId',
    getParentRoute: () => V1MarketplaceAgentsAdminSubmissionsRoute,
  } as any)
const V1SkillsSkillIdVersionsVersionIdContentRoute =
  V1SkillsSkillIdVersionsVersionIdContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => V1SkillsSkillIdVersionsVersionIdRoute,
  } as any)
const V2RemoteHostsHostIdMembersIndexRoute =
  V2RemoteHostsHostIdMembersIndexRouteImport.update({
    id: '/v2/remote/hosts/$hostId/members/',
    path: '/v2/remote/hosts/$hostId/members/',
    getParentRoute: () => rootRouteImport,
  } as any)
const V2RemoteHostsHostIdMembersMembershipIdRoute =
  V2RemoteHostsHostIdMembersMembershipIdRouteImport.update({
    id: '/v2/remote/hosts/$hostId/members/$membershipId',
    path: '/v2/remote/hosts/$hostId/members/$membershipId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app-preview': typeof AppPreviewRoute
  '/join': typeof JoinRoute
  '/report-site': typeof ReportSiteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/apple-app-site-association': typeof DotwellKnownAppleAppSiteAssociationRoute
  '/.well-known/jwks.json': typeof DotwellKnownJwksDotjsonRoute
  '/download/linux': typeof DownloadLinuxRoute
  '/download/macos': typeof DownloadMacosRoute
  '/download/windows': typeof DownloadWindowsRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/guides/rss.xml': typeof GuidesRssDotxmlRoute
  '/health/live': typeof HealthLiveRoute
  '/health/ready': typeof HealthReadyRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/rss.xml': typeof NewsRssDotxmlRoute
  '/plugins/$slug': typeof PluginsSlugRoute
  '/v1/me': typeof V1MeRouteWithChildren
  '/guides/': typeof GuidesIndexRoute
  '/news/': typeof NewsIndexRoute
  '/plugins/': typeof PluginsIndexRoute
  '/plugins/icon/$slug': typeof PluginsIconSlugRoute
  '/v1/auth/logout': typeof V1AuthLogoutRoute
  '/v1/avatars/$userId': typeof V1AvatarsUserIdRoute
  '/v1/me/avatar': typeof V1MeAvatarRoute
  '/v1/me/profile': typeof V1MeProfileRoute
  '/v1/mobile-auth/devices': typeof V1MobileAuthDevicesRouteWithChildren
  '/v1/mobile-auth/redeem': typeof V1MobileAuthRedeemRoute
  '/v1/mobile-auth/session': typeof V1MobileAuthSessionRoute
  '/v1/mobile-auth/ticket': typeof V1MobileAuthTicketRoute
  '/v1/sites/$siteId': typeof V1SitesSiteIdRoute
  '/v1/sites/reports': typeof V1SitesReportsRoute
  '/v1/skills/$skillId': typeof V1SkillsSkillIdRouteWithChildren
  '/v1/skills/mine': typeof V1SkillsMineRoute
  '/v1/team-auth/redeem': typeof V1TeamAuthRedeemRoute
  '/v1/team-auth/ticket': typeof V1TeamAuthTicketRoute
  '/v1/team-hosts/ice-servers': typeof V1TeamHostsIceServersRoute
  '/v1/team-invitations/email': typeof V1TeamInvitationsEmailRoute
  '/v1/team-tunnels/provision': typeof V1TeamTunnelsProvisionRoute
  '/v1/sites/': typeof V1SitesIndexRoute
  '/v1/skills/': typeof V1SkillsIndexRoute
  '/v1/auth/email/start': typeof V1AuthEmailStartRoute
  '/v1/auth/email/verify': typeof V1AuthEmailVerifyRoute
  '/v1/marketplace/agents/$agentId': typeof V1MarketplaceAgentsAgentIdRouteWithChildren
  '/v1/marketplace/agents/mine': typeof V1MarketplaceAgentsMineRoute
  '/v1/mobile-auth/devices/$sessionId': typeof V1MobileAuthDevicesSessionIdRoute
  '/v1/skills/$skillId/content': typeof V1SkillsSkillIdContentRoute
  '/v1/skills/$skillId/icon': typeof V1SkillsSkillIdIconRoute
  '/v1/skills/$skillId/install': typeof V1SkillsSkillIdInstallRoute
  '/v1/skills/admin/submissions': typeof V1SkillsAdminSubmissionsRouteWithChildren
  '/v2/remote/hosts/register': typeof V2RemoteHostsRegisterRoute
  '/v2/remote/invites/$inviteId': typeof V2RemoteInvitesInviteIdRoute
  '/v2/remote/invites/accept': typeof V2RemoteInvitesAcceptRoute
  '/v2/remote/invites/preview': typeof V2RemoteInvitesPreviewRoute
  '/v2/remote/resume/validate': typeof V2RemoteResumeValidateRoute
  '/v1/marketplace/agents/': typeof V1MarketplaceAgentsIndexRoute
  '/v2/remote/hosts/': typeof V2RemoteHostsIndexRoute
  '/v2/remote/sessions/': typeof V2RemoteSessionsIndexRoute
  '/v1/marketplace/agents/$agentId/avatar': typeof V1MarketplaceAgentsAgentIdAvatarRoute
  '/v1/marketplace/agents/$agentId/install': typeof V1MarketplaceAgentsAgentIdInstallRoute
  '/v1/marketplace/agents/admin/submissions': typeof V1MarketplaceAgentsAdminSubmissionsRouteWithChildren
  '/v1/sites/admin/$siteId/block': typeof V1SitesAdminSiteIdBlockRoute
  '/v1/sites/uploads/$uploadId/activate': typeof V1SitesUploadsUploadIdActivateRoute
  '/v1/sites/uploads/$uploadId/file': typeof V1SitesUploadsUploadIdFileRoute
  '/v1/skills/$skillId/versions/$versionId': typeof V1SkillsSkillIdVersionsVersionIdRouteWithChildren
  '/v1/skills/admin/featured/$skillId': typeof V1SkillsAdminFeaturedSkillIdRoute
  '/v1/skills/admin/submissions/$versionId': typeof V1SkillsAdminSubmissionsVersionIdRoute
  '/v2/remote/hosts/$hostId/invites': typeof V2RemoteHostsHostIdInvitesRoute
  '/v2/remote/hosts/$hostId/logo': typeof V2RemoteHostsHostIdLogoRoute
  '/v2/remote/hosts/$hostId/ticket': typeof V2RemoteHostsHostIdTicketRoute
  '/v2/remote/sessions/$sessionId/end': typeof V2RemoteSessionsSessionIdEndRoute
  '/v2/remote/sessions/$sessionId/ticket': typeof V2RemoteSessionsSessionIdTicketRoute
  '/v1/marketplace/agents/admin/featured/$agentId': typeof V1MarketplaceAgentsAdminFeaturedAgentIdRoute
  '/v1/marketplace/agents/admin/submissions/$versionId': typeof V1MarketplaceAgentsAdminSubmissionsVersionIdRoute
  '/v1/skills/$skillId/versions/$versionId/content': typeof V1SkillsSkillIdVersionsVersionIdContentRoute
  '/v2/remote/hosts/$hostId/members/$membershipId': typeof V2RemoteHostsHostIdMembersMembershipIdRoute
  '/v2/remote/hosts/$hostId/members/': typeof V2RemoteHostsHostIdMembersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app-preview': typeof AppPreviewRoute
  '/join': typeof JoinRoute
  '/report-site': typeof ReportSiteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/apple-app-site-association': typeof DotwellKnownAppleAppSiteAssociationRoute
  '/.well-known/jwks.json': typeof DotwellKnownJwksDotjsonRoute
  '/download/linux': typeof DownloadLinuxRoute
  '/download/macos': typeof DownloadMacosRoute
  '/download/windows': typeof DownloadWindowsRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/guides/rss.xml': typeof GuidesRssDotxmlRoute
  '/health/live': typeof HealthLiveRoute
  '/health/ready': typeof HealthReadyRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/rss.xml': typeof NewsRssDotxmlRoute
  '/plugins/$slug': typeof PluginsSlugRoute
  '/v1/me': typeof V1MeRouteWithChildren
  '/guides': typeof GuidesIndexRoute
  '/news': typeof NewsIndexRoute
  '/plugins': typeof PluginsIndexRoute
  '/plugins/icon/$slug': typeof PluginsIconSlugRoute
  '/v1/auth/logout': typeof V1AuthLogoutRoute
  '/v1/avatars/$userId': typeof V1AvatarsUserIdRoute
  '/v1/me/avatar': typeof V1MeAvatarRoute
  '/v1/me/profile': typeof V1MeProfileRoute
  '/v1/mobile-auth/devices': typeof V1MobileAuthDevicesRouteWithChildren
  '/v1/mobile-auth/redeem': typeof V1MobileAuthRedeemRoute
  '/v1/mobile-auth/session': typeof V1MobileAuthSessionRoute
  '/v1/mobile-auth/ticket': typeof V1MobileAuthTicketRoute
  '/v1/sites/$siteId': typeof V1SitesSiteIdRoute
  '/v1/sites/reports': typeof V1SitesReportsRoute
  '/v1/skills/$skillId': typeof V1SkillsSkillIdRouteWithChildren
  '/v1/skills/mine': typeof V1SkillsMineRoute
  '/v1/team-auth/redeem': typeof V1TeamAuthRedeemRoute
  '/v1/team-auth/ticket': typeof V1TeamAuthTicketRoute
  '/v1/team-hosts/ice-servers': typeof V1TeamHostsIceServersRoute
  '/v1/team-invitations/email': typeof V1TeamInvitationsEmailRoute
  '/v1/team-tunnels/provision': typeof V1TeamTunnelsProvisionRoute
  '/v1/sites': typeof V1SitesIndexRoute
  '/v1/skills': typeof V1SkillsIndexRoute
  '/v1/auth/email/start': typeof V1AuthEmailStartRoute
  '/v1/auth/email/verify': typeof V1AuthEmailVerifyRoute
  '/v1/marketplace/agents/$agentId': typeof V1MarketplaceAgentsAgentIdRouteWithChildren
  '/v1/marketplace/agents/mine': typeof V1MarketplaceAgentsMineRoute
  '/v1/mobile-auth/devices/$sessionId': typeof V1MobileAuthDevicesSessionIdRoute
  '/v1/skills/$skillId/content': typeof V1SkillsSkillIdContentRoute
  '/v1/skills/$skillId/icon': typeof V1SkillsSkillIdIconRoute
  '/v1/skills/$skillId/install': typeof V1SkillsSkillIdInstallRoute
  '/v1/skills/admin/submissions': typeof V1SkillsAdminSubmissionsRouteWithChildren
  '/v2/remote/hosts/register': typeof V2RemoteHostsRegisterRoute
  '/v2/remote/invites/$inviteId': typeof V2RemoteInvitesInviteIdRoute
  '/v2/remote/invites/accept': typeof V2RemoteInvitesAcceptRoute
  '/v2/remote/invites/preview': typeof V2RemoteInvitesPreviewRoute
  '/v2/remote/resume/validate': typeof V2RemoteResumeValidateRoute
  '/v1/marketplace/agents': typeof V1MarketplaceAgentsIndexRoute
  '/v2/remote/hosts': typeof V2RemoteHostsIndexRoute
  '/v2/remote/sessions': typeof V2RemoteSessionsIndexRoute
  '/v1/marketplace/agents/$agentId/avatar': typeof V1MarketplaceAgentsAgentIdAvatarRoute
  '/v1/marketplace/agents/$agentId/install': typeof V1MarketplaceAgentsAgentIdInstallRoute
  '/v1/marketplace/agents/admin/submissions': typeof V1MarketplaceAgentsAdminSubmissionsRouteWithChildren
  '/v1/sites/admin/$siteId/block': typeof V1SitesAdminSiteIdBlockRoute
  '/v1/sites/uploads/$uploadId/activate': typeof V1SitesUploadsUploadIdActivateRoute
  '/v1/sites/uploads/$uploadId/file': typeof V1SitesUploadsUploadIdFileRoute
  '/v1/skills/$skillId/versions/$versionId': typeof V1SkillsSkillIdVersionsVersionIdRouteWithChildren
  '/v1/skills/admin/featured/$skillId': typeof V1SkillsAdminFeaturedSkillIdRoute
  '/v1/skills/admin/submissions/$versionId': typeof V1SkillsAdminSubmissionsVersionIdRoute
  '/v2/remote/hosts/$hostId/invites': typeof V2RemoteHostsHostIdInvitesRoute
  '/v2/remote/hosts/$hostId/logo': typeof V2RemoteHostsHostIdLogoRoute
  '/v2/remote/hosts/$hostId/ticket': typeof V2RemoteHostsHostIdTicketRoute
  '/v2/remote/sessions/$sessionId/end': typeof V2RemoteSessionsSessionIdEndRoute
  '/v2/remote/sessions/$sessionId/ticket': typeof V2RemoteSessionsSessionIdTicketRoute
  '/v1/marketplace/agents/admin/featured/$agentId': typeof V1MarketplaceAgentsAdminFeaturedAgentIdRoute
  '/v1/marketplace/agents/admin/submissions/$versionId': typeof V1MarketplaceAgentsAdminSubmissionsVersionIdRoute
  '/v1/skills/$skillId/versions/$versionId/content': typeof V1SkillsSkillIdVersionsVersionIdContentRoute
  '/v2/remote/hosts/$hostId/members/$membershipId': typeof V2RemoteHostsHostIdMembersMembershipIdRoute
  '/v2/remote/hosts/$hostId/members': typeof V2RemoteHostsHostIdMembersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app-preview': typeof AppPreviewRoute
  '/join': typeof JoinRoute
  '/report-site': typeof ReportSiteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/apple-app-site-association': typeof DotwellKnownAppleAppSiteAssociationRoute
  '/.well-known/jwks.json': typeof DotwellKnownJwksDotjsonRoute
  '/download/linux': typeof DownloadLinuxRoute
  '/download/macos': typeof DownloadMacosRoute
  '/download/windows': typeof DownloadWindowsRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/guides/rss.xml': typeof GuidesRssDotxmlRoute
  '/health/live': typeof HealthLiveRoute
  '/health/ready': typeof HealthReadyRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/rss.xml': typeof NewsRssDotxmlRoute
  '/plugins/$slug': typeof PluginsSlugRoute
  '/v1/me': typeof V1MeRouteWithChildren
  '/guides/': typeof GuidesIndexRoute
  '/news/': typeof NewsIndexRoute
  '/plugins/': typeof PluginsIndexRoute
  '/plugins/icon/$slug': typeof PluginsIconSlugRoute
  '/v1/auth/logout': typeof V1AuthLogoutRoute
  '/v1/avatars/$userId': typeof V1AvatarsUserIdRoute
  '/v1/me/avatar': typeof V1MeAvatarRoute
  '/v1/me/profile': typeof V1MeProfileRoute
  '/v1/mobile-auth/devices': typeof V1MobileAuthDevicesRouteWithChildren
  '/v1/mobile-auth/redeem': typeof V1MobileAuthRedeemRoute
  '/v1/mobile-auth/session': typeof V1MobileAuthSessionRoute
  '/v1/mobile-auth/ticket': typeof V1MobileAuthTicketRoute
  '/v1/sites/$siteId': typeof V1SitesSiteIdRoute
  '/v1/sites/reports': typeof V1SitesReportsRoute
  '/v1/skills/$skillId': typeof V1SkillsSkillIdRouteWithChildren
  '/v1/skills/mine': typeof V1SkillsMineRoute
  '/v1/team-auth/redeem': typeof V1TeamAuthRedeemRoute
  '/v1/team-auth/ticket': typeof V1TeamAuthTicketRoute
  '/v1/team-hosts/ice-servers': typeof V1TeamHostsIceServersRoute
  '/v1/team-invitations/email': typeof V1TeamInvitationsEmailRoute
  '/v1/team-tunnels/provision': typeof V1TeamTunnelsProvisionRoute
  '/v1/sites/': typeof V1SitesIndexRoute
  '/v1/skills/': typeof V1SkillsIndexRoute
  '/v1/auth/email/start': typeof V1AuthEmailStartRoute
  '/v1/auth/email/verify': typeof V1AuthEmailVerifyRoute
  '/v1/marketplace/agents/$agentId': typeof V1MarketplaceAgentsAgentIdRouteWithChildren
  '/v1/marketplace/agents/mine': typeof V1MarketplaceAgentsMineRoute
  '/v1/mobile-auth/devices/$sessionId': typeof V1MobileAuthDevicesSessionIdRoute
  '/v1/skills/$skillId/content': typeof V1SkillsSkillIdContentRoute
  '/v1/skills/$skillId/icon': typeof V1SkillsSkillIdIconRoute
  '/v1/skills/$skillId/install': typeof V1SkillsSkillIdInstallRoute
  '/v1/skills/admin/submissions': typeof V1SkillsAdminSubmissionsRouteWithChildren
  '/v2/remote/hosts/register': typeof V2RemoteHostsRegisterRoute
  '/v2/remote/invites/$inviteId': typeof V2RemoteInvitesInviteIdRoute
  '/v2/remote/invites/accept': typeof V2RemoteInvitesAcceptRoute
  '/v2/remote/invites/preview': typeof V2RemoteInvitesPreviewRoute
  '/v2/remote/resume/validate': typeof V2RemoteResumeValidateRoute
  '/v1/marketplace/agents/': typeof V1MarketplaceAgentsIndexRoute
  '/v2/remote/hosts/': typeof V2RemoteHostsIndexRoute
  '/v2/remote/sessions/': typeof V2RemoteSessionsIndexRoute
  '/v1/marketplace/agents/$agentId/avatar': typeof V1MarketplaceAgentsAgentIdAvatarRoute
  '/v1/marketplace/agents/$agentId/install': typeof V1MarketplaceAgentsAgentIdInstallRoute
  '/v1/marketplace/agents/admin/submissions': typeof V1MarketplaceAgentsAdminSubmissionsRouteWithChildren
  '/v1/sites/admin/$siteId/block': typeof V1SitesAdminSiteIdBlockRoute
  '/v1/sites/uploads/$uploadId/activate': typeof V1SitesUploadsUploadIdActivateRoute
  '/v1/sites/uploads/$uploadId/file': typeof V1SitesUploadsUploadIdFileRoute
  '/v1/skills/$skillId/versions/$versionId': typeof V1SkillsSkillIdVersionsVersionIdRouteWithChildren
  '/v1/skills/admin/featured/$skillId': typeof V1SkillsAdminFeaturedSkillIdRoute
  '/v1/skills/admin/submissions/$versionId': typeof V1SkillsAdminSubmissionsVersionIdRoute
  '/v2/remote/hosts/$hostId/invites': typeof V2RemoteHostsHostIdInvitesRoute
  '/v2/remote/hosts/$hostId/logo': typeof V2RemoteHostsHostIdLogoRoute
  '/v2/remote/hosts/$hostId/ticket': typeof V2RemoteHostsHostIdTicketRoute
  '/v2/remote/sessions/$sessionId/end': typeof V2RemoteSessionsSessionIdEndRoute
  '/v2/remote/sessions/$sessionId/ticket': typeof V2RemoteSessionsSessionIdTicketRoute
  '/v1/marketplace/agents/admin/featured/$agentId': typeof V1MarketplaceAgentsAdminFeaturedAgentIdRoute
  '/v1/marketplace/agents/admin/submissions/$versionId': typeof V1MarketplaceAgentsAdminSubmissionsVersionIdRoute
  '/v1/skills/$skillId/versions/$versionId/content': typeof V1SkillsSkillIdVersionsVersionIdContentRoute
  '/v2/remote/hosts/$hostId/members/$membershipId': typeof V2RemoteHostsHostIdMembersMembershipIdRoute
  '/v2/remote/hosts/$hostId/members/': typeof V2RemoteHostsHostIdMembersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app-preview'
    | '/join'
    | '/report-site'
    | '/sitemap.xml'
    | '/.well-known/apple-app-site-association'
    | '/.well-known/jwks.json'
    | '/download/linux'
    | '/download/macos'
    | '/download/windows'
    | '/guides/$slug'
    | '/guides/rss.xml'
    | '/health/live'
    | '/health/ready'
    | '/news/$slug'
    | '/news/rss.xml'
    | '/plugins/$slug'
    | '/v1/me'
    | '/guides/'
    | '/news/'
    | '/plugins/'
    | '/plugins/icon/$slug'
    | '/v1/auth/logout'
    | '/v1/avatars/$userId'
    | '/v1/me/avatar'
    | '/v1/me/profile'
    | '/v1/mobile-auth/devices'
    | '/v1/mobile-auth/redeem'
    | '/v1/mobile-auth/session'
    | '/v1/mobile-auth/ticket'
    | '/v1/sites/$siteId'
    | '/v1/sites/reports'
    | '/v1/skills/$skillId'
    | '/v1/skills/mine'
    | '/v1/team-auth/redeem'
    | '/v1/team-auth/ticket'
    | '/v1/team-hosts/ice-servers'
    | '/v1/team-invitations/email'
    | '/v1/team-tunnels/provision'
    | '/v1/sites/'
    | '/v1/skills/'
    | '/v1/auth/email/start'
    | '/v1/auth/email/verify'
    | '/v1/marketplace/agents/$agentId'
    | '/v1/marketplace/agents/mine'
    | '/v1/mobile-auth/devices/$sessionId'
    | '/v1/skills/$skillId/content'
    | '/v1/skills/$skillId/icon'
    | '/v1/skills/$skillId/install'
    | '/v1/skills/admin/submissions'
    | '/v2/remote/hosts/register'
    | '/v2/remote/invites/$inviteId'
    | '/v2/remote/invites/accept'
    | '/v2/remote/invites/preview'
    | '/v2/remote/resume/validate'
    | '/v1/marketplace/agents/'
    | '/v2/remote/hosts/'
    | '/v2/remote/sessions/'
    | '/v1/marketplace/agents/$agentId/avatar'
    | '/v1/marketplace/agents/$agentId/install'
    | '/v1/marketplace/agents/admin/submissions'
    | '/v1/sites/admin/$siteId/block'
    | '/v1/sites/uploads/$uploadId/activate'
    | '/v1/sites/uploads/$uploadId/file'
    | '/v1/skills/$skillId/versions/$versionId'
    | '/v1/skills/admin/featured/$skillId'
    | '/v1/skills/admin/submissions/$versionId'
    | '/v2/remote/hosts/$hostId/invites'
    | '/v2/remote/hosts/$hostId/logo'
    | '/v2/remote/hosts/$hostId/ticket'
    | '/v2/remote/sessions/$sessionId/end'
    | '/v2/remote/sessions/$sessionId/ticket'
    | '/v1/marketplace/agents/admin/featured/$agentId'
    | '/v1/marketplace/agents/admin/submissions/$versionId'
    | '/v1/skills/$skillId/versions/$versionId/content'
    | '/v2/remote/hosts/$hostId/members/$membershipId'
    | '/v2/remote/hosts/$hostId/members/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app-preview'
    | '/join'
    | '/report-site'
    | '/sitemap.xml'
    | '/.well-known/apple-app-site-association'
    | '/.well-known/jwks.json'
    | '/download/linux'
    | '/download/macos'
    | '/download/windows'
    | '/guides/$slug'
    | '/guides/rss.xml'
    | '/health/live'
    | '/health/ready'
    | '/news/$slug'
    | '/news/rss.xml'
    | '/plugins/$slug'
    | '/v1/me'
    | '/guides'
    | '/news'
    | '/plugins'
    | '/plugins/icon/$slug'
    | '/v1/auth/logout'
    | '/v1/avatars/$userId'
    | '/v1/me/avatar'
    | '/v1/me/profile'
    | '/v1/mobile-auth/devices'
    | '/v1/mobile-auth/redeem'
    | '/v1/mobile-auth/session'
    | '/v1/mobile-auth/ticket'
    | '/v1/sites/$siteId'
    | '/v1/sites/reports'
    | '/v1/skills/$skillId'
    | '/v1/skills/mine'
    | '/v1/team-auth/redeem'
    | '/v1/team-auth/ticket'
    | '/v1/team-hosts/ice-servers'
    | '/v1/team-invitations/email'
    | '/v1/team-tunnels/provision'
    | '/v1/sites'
    | '/v1/skills'
    | '/v1/auth/email/start'
    | '/v1/auth/email/verify'
    | '/v1/marketplace/agents/$agentId'
    | '/v1/marketplace/agents/mine'
    | '/v1/mobile-auth/devices/$sessionId'
    | '/v1/skills/$skillId/content'
    | '/v1/skills/$skillId/icon'
    | '/v1/skills/$skillId/install'
    | '/v1/skills/admin/submissions'
    | '/v2/remote/hosts/register'
    | '/v2/remote/invites/$inviteId'
    | '/v2/remote/invites/accept'
    | '/v2/remote/invites/preview'
    | '/v2/remote/resume/validate'
    | '/v1/marketplace/agents'
    | '/v2/remote/hosts'
    | '/v2/remote/sessions'
    | '/v1/marketplace/agents/$agentId/avatar'
    | '/v1/marketplace/agents/$agentId/install'
    | '/v1/marketplace/agents/admin/submissions'
    | '/v1/sites/admin/$siteId/block'
    | '/v1/sites/uploads/$uploadId/activate'
    | '/v1/sites/uploads/$uploadId/file'
    | '/v1/skills/$skillId/versions/$versionId'
    | '/v1/skills/admin/featured/$skillId'
    | '/v1/skills/admin/submissions/$versionId'
    | '/v2/remote/hosts/$hostId/invites'
    | '/v2/remote/hosts/$hostId/logo'
    | '/v2/remote/hosts/$hostId/ticket'
    | '/v2/remote/sessions/$sessionId/end'
    | '/v2/remote/sessions/$sessionId/ticket'
    | '/v1/marketplace/agents/admin/featured/$agentId'
    | '/v1/marketplace/agents/admin/submissions/$versionId'
    | '/v1/skills/$skillId/versions/$versionId/content'
    | '/v2/remote/hosts/$hostId/members/$membershipId'
    | '/v2/remote/hosts/$hostId/members'
  id:
    | '__root__'
    | '/'
    | '/app-preview'
    | '/join'
    | '/report-site'
    | '/sitemap.xml'
    | '/.well-known/apple-app-site-association'
    | '/.well-known/jwks.json'
    | '/download/linux'
    | '/download/macos'
    | '/download/windows'
    | '/guides/$slug'
    | '/guides/rss.xml'
    | '/health/live'
    | '/health/ready'
    | '/news/$slug'
    | '/news/rss.xml'
    | '/plugins/$slug'
    | '/v1/me'
    | '/guides/'
    | '/news/'
    | '/plugins/'
    | '/plugins/icon/$slug'
    | '/v1/auth/logout'
    | '/v1/avatars/$userId'
    | '/v1/me/avatar'
    | '/v1/me/profile'
    | '/v1/mobile-auth/devices'
    | '/v1/mobile-auth/redeem'
    | '/v1/mobile-auth/session'
    | '/v1/mobile-auth/ticket'
    | '/v1/sites/$siteId'
    | '/v1/sites/reports'
    | '/v1/skills/$skillId'
    | '/v1/skills/mine'
    | '/v1/team-auth/redeem'
    | '/v1/team-auth/ticket'
    | '/v1/team-hosts/ice-servers'
    | '/v1/team-invitations/email'
    | '/v1/team-tunnels/provision'
    | '/v1/sites/'
    | '/v1/skills/'
    | '/v1/auth/email/start'
    | '/v1/auth/email/verify'
    | '/v1/marketplace/agents/$agentId'
    | '/v1/marketplace/agents/mine'
    | '/v1/mobile-auth/devices/$sessionId'
    | '/v1/skills/$skillId/content'
    | '/v1/skills/$skillId/icon'
    | '/v1/skills/$skillId/install'
    | '/v1/skills/admin/submissions'
    | '/v2/remote/hosts/register'
    | '/v2/remote/invites/$inviteId'
    | '/v2/remote/invites/accept'
    | '/v2/remote/invites/preview'
    | '/v2/remote/resume/validate'
    | '/v1/marketplace/agents/'
    | '/v2/remote/hosts/'
    | '/v2/remote/sessions/'
    | '/v1/marketplace/agents/$agentId/avatar'
    | '/v1/marketplace/agents/$agentId/install'
    | '/v1/marketplace/agents/admin/submissions'
    | '/v1/sites/admin/$siteId/block'
    | '/v1/sites/uploads/$uploadId/activate'
    | '/v1/sites/uploads/$uploadId/file'
    | '/v1/skills/$skillId/versions/$versionId'
    | '/v1/skills/admin/featured/$skillId'
    | '/v1/skills/admin/submissions/$versionId'
    | '/v2/remote/hosts/$hostId/invites'
    | '/v2/remote/hosts/$hostId/logo'
    | '/v2/remote/hosts/$hostId/ticket'
    | '/v2/remote/sessions/$sessionId/end'
    | '/v2/remote/sessions/$sessionId/ticket'
    | '/v1/marketplace/agents/admin/featured/$agentId'
    | '/v1/marketplace/agents/admin/submissions/$versionId'
    | '/v1/skills/$skillId/versions/$versionId/content'
    | '/v2/remote/hosts/$hostId/members/$membershipId'
    | '/v2/remote/hosts/$hostId/members/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppPreviewRoute: typeof AppPreviewRoute
  JoinRoute: typeof JoinRoute
  ReportSiteRoute: typeof ReportSiteRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DotwellKnownAppleAppSiteAssociationRoute: typeof DotwellKnownAppleAppSiteAssociationRoute
  DotwellKnownJwksDotjsonRoute: typeof DotwellKnownJwksDotjsonRoute
  DownloadLinuxRoute: typeof DownloadLinuxRoute
  DownloadMacosRoute: typeof DownloadMacosRoute
  DownloadWindowsRoute: typeof DownloadWindowsRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  GuidesRssDotxmlRoute: typeof GuidesRssDotxmlRoute
  HealthLiveRoute: typeof HealthLiveRoute
  HealthReadyRoute: typeof HealthReadyRoute
  NewsSlugRoute: typeof NewsSlugRoute
  NewsRssDotxmlRoute: typeof NewsRssDotxmlRoute
  PluginsSlugRoute: typeof PluginsSlugRoute
  V1MeRoute: typeof V1MeRouteWithChildren
  GuidesIndexRoute: typeof GuidesIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  PluginsIndexRoute: typeof PluginsIndexRoute
  PluginsIconSlugRoute: typeof PluginsIconSlugRoute
  V1AuthLogoutRoute: typeof V1AuthLogoutRoute
  V1AvatarsUserIdRoute: typeof V1AvatarsUserIdRoute
  V1MobileAuthDevicesRoute: typeof V1MobileAuthDevicesRouteWithChildren
  V1MobileAuthRedeemRoute: typeof V1MobileAuthRedeemRoute
  V1MobileAuthSessionRoute: typeof V1MobileAuthSessionRoute
  V1MobileAuthTicketRoute: typeof V1MobileAuthTicketRoute
  V1SitesSiteIdRoute: typeof V1SitesSiteIdRoute
  V1SitesReportsRoute: typeof V1SitesReportsRoute
  V1SkillsSkillIdRoute: typeof V1SkillsSkillIdRouteWithChildren
  V1SkillsMineRoute: typeof V1SkillsMineRoute
  V1TeamAuthRedeemRoute: typeof V1TeamAuthRedeemRoute
  V1TeamAuthTicketRoute: typeof V1TeamAuthTicketRoute
  V1TeamHostsIceServersRoute: typeof V1TeamHostsIceServersRoute
  V1TeamInvitationsEmailRoute: typeof V1TeamInvitationsEmailRoute
  V1TeamTunnelsProvisionRoute: typeof V1TeamTunnelsProvisionRoute
  V1SitesIndexRoute: typeof V1SitesIndexRoute
  V1SkillsIndexRoute: typeof V1SkillsIndexRoute
  V1AuthEmailStartRoute: typeof V1AuthEmailStartRoute
  V1AuthEmailVerifyRoute: typeof V1AuthEmailVerifyRoute
  V1MarketplaceAgentsAgentIdRoute: typeof V1MarketplaceAgentsAgentIdRouteWithChildren
  V1MarketplaceAgentsMineRoute: typeof V1MarketplaceAgentsMineRoute
  V1SkillsAdminSubmissionsRoute: typeof V1SkillsAdminSubmissionsRouteWithChildren
  V2RemoteHostsRegisterRoute: typeof V2RemoteHostsRegisterRoute
  V2RemoteInvitesInviteIdRoute: typeof V2RemoteInvitesInviteIdRoute
  V2RemoteInvitesAcceptRoute: typeof V2RemoteInvitesAcceptRoute
  V2RemoteInvitesPreviewRoute: typeof V2RemoteInvitesPreviewRoute
  V2RemoteResumeValidateRoute: typeof V2RemoteResumeValidateRoute
  V1MarketplaceAgentsIndexRoute: typeof V1MarketplaceAgentsIndexRoute
  V2RemoteHostsIndexRoute: typeof V2RemoteHostsIndexRoute
  V2RemoteSessionsIndexRoute: typeof V2RemoteSessionsIndexRoute
  V1MarketplaceAgentsAdminSubmissionsRoute: typeof V1MarketplaceAgentsAdminSubmissionsRouteWithChildren
  V1SitesAdminSiteIdBlockRoute: typeof V1SitesAdminSiteIdBlockRoute
  V1SitesUploadsUploadIdActivateRoute: typeof V1SitesUploadsUploadIdActivateRoute
  V1SitesUploadsUploadIdFileRoute: typeof V1SitesUploadsUploadIdFileRoute
  V1SkillsAdminFeaturedSkillIdRoute: typeof V1SkillsAdminFeaturedSkillIdRoute
  V2RemoteHostsHostIdInvitesRoute: typeof V2RemoteHostsHostIdInvitesRoute
  V2RemoteHostsHostIdLogoRoute: typeof V2RemoteHostsHostIdLogoRoute
  V2RemoteHostsHostIdTicketRoute: typeof V2RemoteHostsHostIdTicketRoute
  V2RemoteSessionsSessionIdEndRoute: typeof V2RemoteSessionsSessionIdEndRoute
  V2RemoteSessionsSessionIdTicketRoute: typeof V2RemoteSessionsSessionIdTicketRoute
  V1MarketplaceAgentsAdminFeaturedAgentIdRoute: typeof V1MarketplaceAgentsAdminFeaturedAgentIdRoute
  V2RemoteHostsHostIdMembersMembershipIdRoute: typeof V2RemoteHostsHostIdMembersMembershipIdRoute
  V2RemoteHostsHostIdMembersIndexRoute: typeof V2RemoteHostsHostIdMembersIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-preview': {
      id: '/app-preview'
      path: '/app-preview'
      fullPath: '/app-preview'
      preLoaderRoute: typeof AppPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-site': {
      id: '/report-site'
      path: '/report-site'
      fullPath: '/report-site'
      preLoaderRoute: typeof ReportSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/apple-app-site-association': {
      id: '/.well-known/apple-app-site-association'
      path: '/.well-known/apple-app-site-association'
      fullPath: '/.well-known/apple-app-site-association'
      preLoaderRoute: typeof DotwellKnownAppleAppSiteAssociationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/jwks.json': {
      id: '/.well-known/jwks.json'
      path: '/.well-known/jwks.json'
      fullPath: '/.well-known/jwks.json'
      preLoaderRoute: typeof DotwellKnownJwksDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/linux': {
      id: '/download/linux'
      path: '/download/linux'
      fullPath: '/download/linux'
      preLoaderRoute: typeof DownloadLinuxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/macos': {
      id: '/download/macos'
      path: '/download/macos'
      fullPath: '/download/macos'
      preLoaderRoute: typeof DownloadMacosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/windows': {
      id: '/download/windows'
      path: '/download/windows'
      fullPath: '/download/windows'
      preLoaderRoute: typeof DownloadWindowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/rss.xml': {
      id: '/guides/rss.xml'
      path: '/guides/rss.xml'
      fullPath: '/guides/rss.xml'
      preLoaderRoute: typeof GuidesRssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/live': {
      id: '/health/live'
      path: '/health/live'
      fullPath: '/health/live'
      preLoaderRoute: typeof HealthLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/ready': {
      id: '/health/ready'
      path: '/health/ready'
      fullPath: '/health/ready'
      preLoaderRoute: typeof HealthReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/rss.xml': {
      id: '/news/rss.xml'
      path: '/news/rss.xml'
      fullPath: '/news/rss.xml'
      preLoaderRoute: typeof NewsRssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/': {
      id: '/plugins/'
      path: '/plugins'
      fullPath: '/plugins/'
      preLoaderRoute: typeof PluginsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$slug': {
      id: '/plugins/$slug'
      path: '/plugins/$slug'
      fullPath: '/plugins/$slug'
      preLoaderRoute: typeof PluginsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/me': {
      id: '/v1/me'
      path: '/v1/me'
      fullPath: '/v1/me'
      preLoaderRoute: typeof V1MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/icon/$slug': {
      id: '/plugins/icon/$slug'
      path: '/plugins/icon/$slug'
      fullPath: '/plugins/icon/$slug'
      preLoaderRoute: typeof PluginsIconSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/auth/logout': {
      id: '/v1/auth/logout'
      path: '/v1/auth/logout'
      fullPath: '/v1/auth/logout'
      preLoaderRoute: typeof V1AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/avatars/$userId': {
      id: '/v1/avatars/$userId'
      path: '/v1/avatars/$userId'
      fullPath: '/v1/avatars/$userId'
      preLoaderRoute: typeof V1AvatarsUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/me/avatar': {
      id: '/v1/me/avatar'
      path: '/avatar'
      fullPath: '/v1/me/avatar'
      preLoaderRoute: typeof V1MeAvatarRouteImport
      parentRoute: typeof V1MeRoute
    }
    '/v1/me/profile': {
      id: '/v1/me/profile'
      path: '/profile'
      fullPath: '/v1/me/profile'
      preLoaderRoute: typeof V1MeProfileRouteImport
      parentRoute: typeof V1MeRoute
    }
    '/v1/mobile-auth/devices': {
      id: '/v1/mobile-auth/devices'
      path: '/v1/mobile-auth/devices'
      fullPath: '/v1/mobile-auth/devices'
      preLoaderRoute: typeof V1MobileAuthDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/mobile-auth/redeem': {
      id: '/v1/mobile-auth/redeem'
      path: '/v1/mobile-auth/redeem'
      fullPath: '/v1/mobile-auth/redeem'
      preLoaderRoute: typeof V1MobileAuthRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/mobile-auth/session': {
      id: '/v1/mobile-auth/session'
      path: '/v1/mobile-auth/session'
      fullPath: '/v1/mobile-auth/session'
      preLoaderRoute: typeof V1MobileAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/mobile-auth/ticket': {
      id: '/v1/mobile-auth/ticket'
      path: '/v1/mobile-auth/ticket'
      fullPath: '/v1/mobile-auth/ticket'
      preLoaderRoute: typeof V1MobileAuthTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/sites/': {
      id: '/v1/sites/'
      path: '/v1/sites'
      fullPath: '/v1/sites/'
      preLoaderRoute: typeof V1SitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/sites/$siteId': {
      id: '/v1/sites/$siteId'
      path: '/v1/sites/$siteId'
      fullPath: '/v1/sites/$siteId'
      preLoaderRoute: typeof V1SitesSiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/sites/reports': {
      id: '/v1/sites/reports'
      path: '/v1/sites/reports'
      fullPath: '/v1/sites/reports'
      preLoaderRoute: typeof V1SitesReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/skills/': {
      id: '/v1/skills/'
      path: '/v1/skills'
      fullPath: '/v1/skills/'
      preLoaderRoute: typeof V1SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/skills/$skillId': {
      id: '/v1/skills/$skillId'
      path: '/v1/skills/$skillId'
      fullPath: '/v1/skills/$skillId'
      preLoaderRoute: typeof V1SkillsSkillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/skills/mine': {
      id: '/v1/skills/mine'
      path: '/v1/skills/mine'
      fullPath: '/v1/skills/mine'
      preLoaderRoute: typeof V1SkillsMineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/team-auth/redeem': {
      id: '/v1/team-auth/redeem'
      path: '/v1/team-auth/redeem'
      fullPath: '/v1/team-auth/redeem'
      preLoaderRoute: typeof V1TeamAuthRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/team-auth/ticket': {
      id: '/v1/team-auth/ticket'
      path: '/v1/team-auth/ticket'
      fullPath: '/v1/team-auth/ticket'
      preLoaderRoute: typeof V1TeamAuthTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/team-hosts/ice-servers': {
      id: '/v1/team-hosts/ice-servers'
      path: '/v1/team-hosts/ice-servers'
      fullPath: '/v1/team-hosts/ice-servers'
      preLoaderRoute: typeof V1TeamHostsIceServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/team-invitations/email': {
      id: '/v1/team-invitations/email'
      path: '/v1/team-invitations/email'
      fullPath: '/v1/team-invitations/email'
      preLoaderRoute: typeof V1TeamInvitationsEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/team-tunnels/provision': {
      id: '/v1/team-tunnels/provision'
      path: '/v1/team-tunnels/provision'
      fullPath: '/v1/team-tunnels/provision'
      preLoaderRoute: typeof V1TeamTunnelsProvisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/auth/email/start': {
      id: '/v1/auth/email/start'
      path: '/v1/auth/email/start'
      fullPath: '/v1/auth/email/start'
      preLoaderRoute: typeof V1AuthEmailStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/auth/email/verify': {
      id: '/v1/auth/email/verify'
      path: '/v1/auth/email/verify'
      fullPath: '/v1/auth/email/verify'
      preLoaderRoute: typeof V1AuthEmailVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/marketplace/agents/': {
      id: '/v1/marketplace/agents/'
      path: '/v1/marketplace/agents'
      fullPath: '/v1/marketplace/agents/'
      preLoaderRoute: typeof V1MarketplaceAgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/marketplace/agents/$agentId': {
      id: '/v1/marketplace/agents/$agentId'
      path: '/v1/marketplace/agents/$agentId'
      fullPath: '/v1/marketplace/agents/$agentId'
      preLoaderRoute: typeof V1MarketplaceAgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/marketplace/agents/mine': {
      id: '/v1/marketplace/agents/mine'
      path: '/v1/marketplace/agents/mine'
      fullPath: '/v1/marketplace/agents/mine'
      preLoaderRoute: typeof V1MarketplaceAgentsMineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/mobile-auth/devices/$sessionId': {
      id: '/v1/mobile-auth/devices/$sessionId'
      path: '/$sessionId'
      fullPath: '/v1/mobile-auth/devices/$sessionId'
      preLoaderRoute: typeof V1MobileAuthDevicesSessionIdRouteImport
      parentRoute: typeof V1MobileAuthDevicesRoute
    }
    '/v1/skills/$skillId/content': {
      id: '/v1/skills/$skillId/content'
      path: '/content'
      fullPath: '/v1/skills/$skillId/content'
      preLoaderRoute: typeof V1SkillsSkillIdContentRouteImport
      parentRoute: typeof V1SkillsSkillIdRoute
    }
    '/v1/skills/$skillId/icon': {
      id: '/v1/skills/$skillId/icon'
      path: '/icon'
      fullPath: '/v1/skills/$skillId/icon'
      preLoaderRoute: typeof V1SkillsSkillIdIconRouteImport
      parentRoute: typeof V1SkillsSkillIdRoute
    }
    '/v1/skills/$skillId/install': {
      id: '/v1/skills/$skillId/install'
      path: '/install'
      fullPath: '/v1/skills/$skillId/install'
      preLoaderRoute: typeof V1SkillsSkillIdInstallRouteImport
      parentRoute: typeof V1SkillsSkillIdRoute
    }
    '/v1/skills/admin/submissions': {
      id: '/v1/skills/admin/submissions'
      path: '/v1/skills/admin/submissions'
      fullPath: '/v1/skills/admin/submissions'
      preLoaderRoute: typeof V1SkillsAdminSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/remote/hosts/': {
      id: '/v2/remote/hosts/'
      path: '/v2/remote/hosts'
      fullPath: '/v2/remote/hosts/'
      preLoaderRoute: typeof V2RemoteHostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/remote/hosts/register': {
      id: '/v2/remote/hosts/register'
      path: '/v2/remote/hosts/register'
      fullPath: '/v2/remote/hosts/register'
      preLoaderRoute: typeof V2RemoteHostsRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/remote/invites/$inviteId': {
      id: '/v2/remote/invites/$inviteId'
      path: '/v2/remote/invites/$inviteId'
      fullPath: '/v2/remote/invites/$inviteId'
      preLoaderRoute: typeof V2RemoteInvitesInviteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/remote/invites/accept': {
      id: '/v2/remote/invites/accept'
      path: '/v2/remote/invites/accept'
      fullPath: '/v2/remote/invites/accept'
      preLoaderRoute: typeof V2RemoteInvitesAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/remote/invites/preview': {
      id: '/v2/remote/invites/preview'
      path: '/v2/remote/invites/preview'
      fullPath: '/v2/remote/invites/preview'
      preLoaderRoute: typeof V2RemoteInvitesPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/remote/resume/validate': {
      id: '/v2/remote/resume/validate'
      path: '/v2/remote/resume/validate'
      fullPath: '/v2/remote/resume/validate'
      preLoaderRoute: typeof V2RemoteResumeValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/remote/sessions/': {
      id: '/v2/remote/sessions/'
      path: '/v2/remote/sessions'
      fullPath: '/v2/remote/sessions/'
      preLoaderRoute: typeof V2RemoteSessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/marketplace/agents/$agentId/avatar': {
      id: '/v1/marketplace/agents/$agentId/avatar'
      path: '/avatar'
      fullPath: '/v1/marketplace/agents/$agentId/avatar'
      preLoaderRoute: typeof V1MarketplaceAgentsAgentIdAvatarRouteImport
      parentRoute: typeof V1MarketplaceAgentsAgentIdRoute
    }
    '/v1/marketplace/agents/$agentId/install': {
      id: '/v1/marketplace/agents/$agentId/install'
      path: '/install'
      fullPath: '/v1/marketplace/agents/$agentId/install'
      preLoaderRoute: typeof V1MarketplaceAgentsAgentIdInstallRouteImport
      parentRoute: typeof V1MarketplaceAgentsAgentIdRoute
    }
    '/v1/marketplace/agents/admin/submissions': {
      id: '/v1/marketplace/agents/admin/submissions'
      path: '/v1/marketplace/agents/admin/submissions'
      fullPath: '/v1/marketplace/agents/admin/submissions'
      preLoaderRoute: typeof V1MarketplaceAgentsAdminSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/sites/admin/$siteId/block': {
      id: '/v1/sites/admin/$siteId/block'
      path: '/v1/sites/admin/$siteId/block'
      fullPath: '/v1/sites/admin/$siteId/block'
      preLoaderRoute: typeof V1SitesAdminSiteIdBlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/sites/uploads/$uploadId/activate': {
      id: '/v1/sites/uploads/$uploadId/activate'
      path: '/v1/sites/uploads/$uploadId/activate'
      fullPath: '/v1/sites/uploads/$uploadId/activate'
      preLoaderRoute: typeof V1SitesUploadsUploadIdActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/sites/uploads/$uploadId/file': {
      id: '/v1/sites/uploads/$uploadId/file'
      path: '/v1/sites/uploads/$uploadId/file'
      fullPath: '/v1/sites/uploads/$uploadId/file'
      preLoaderRoute: typeof V1SitesUploadsUploadIdFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/skills/$skillId/versions/$versionId': {
      id: '/v1/skills/$skillId/versions/$versionId'
      path: '/versions/$versionId'
      fullPath: '/v1/skills/$skillId/versions/$versionId'
      preLoaderRoute: typeof V1SkillsSkillIdVersionsVersionIdRouteImport
      parentRoute: typeof V1SkillsSkillIdRoute
    }
    '/v1/skills/admin/featured/$skillId': {
      id: '/v1/skills/admin/featured/$skillId'
      path: '/v1/skills/admin/featured/$skillId'
      fullPath: '/v1/skills/admin/featured/$skillId'
      preLoaderRoute: typeof V1SkillsAdminFeaturedSkillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/skills/admin/submissions/$versionId': {
      id: '/v1/skills/admin/submissions/$versionId'
      path: '/$versionId'
      fullPath: '/v1/skills/admin/submissions/$versionId'
      preLoaderRoute: typeof V1SkillsAdminSubmissionsVersionIdRouteImport
      parentRoute: typeof V1SkillsAdminSubmissionsRoute
    }
    '/v2/remote/hosts/$hostId/invites': {
      id: '/v2/remote/hosts/$hostId/invites'
      path: '/v2/remote/hosts/$hostId/invites'
      fullPath: '/v2/remote/hosts/$hostId/invites'
      preLoaderRoute: typeof V2RemoteHostsHostIdInvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/remote/hosts/$hostId/logo': {
      id: '/v2/remote/hosts/$hostId/logo'
      path: '/v2/remote/hosts/$hostId/logo'
      fullPath: '/v2/remote/hosts/$hostId/logo'
      preLoaderRoute: typeof V2RemoteHostsHostIdLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/remote/hosts/$hostId/ticket': {
      id: '/v2/remote/hosts/$hostId/ticket'
      path: '/v2/remote/hosts/$hostId/ticket'
      fullPath: '/v2/remote/hosts/$hostId/ticket'
      preLoaderRoute: typeof V2RemoteHostsHostIdTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/remote/sessions/$sessionId/end': {
      id: '/v2/remote/sessions/$sessionId/end'
      path: '/v2/remote/sessions/$sessionId/end'
      fullPath: '/v2/remote/sessions/$sessionId/end'
      preLoaderRoute: typeof V2RemoteSessionsSessionIdEndRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/remote/sessions/$sessionId/ticket': {
      id: '/v2/remote/sessions/$sessionId/ticket'
      path: '/v2/remote/sessions/$sessionId/ticket'
      fullPath: '/v2/remote/sessions/$sessionId/ticket'
      preLoaderRoute: typeof V2RemoteSessionsSessionIdTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/marketplace/agents/admin/featured/$agentId': {
      id: '/v1/marketplace/agents/admin/featured/$agentId'
      path: '/v1/marketplace/agents/admin/featured/$agentId'
      fullPath: '/v1/marketplace/agents/admin/featured/$agentId'
      preLoaderRoute: typeof V1MarketplaceAgentsAdminFeaturedAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/marketplace/agents/admin/submissions/$versionId': {
      id: '/v1/marketplace/agents/admin/submissions/$versionId'
      path: '/$versionId'
      fullPath: '/v1/marketplace/agents/admin/submissions/$versionId'
      preLoaderRoute: typeof V1MarketplaceAgentsAdminSubmissionsVersionIdRouteImport
      parentRoute: typeof V1MarketplaceAgentsAdminSubmissionsRoute
    }
    '/v1/skills/$skillId/versions/$versionId/content': {
      id: '/v1/skills/$skillId/versions/$versionId/content'
      path: '/content'
      fullPath: '/v1/skills/$skillId/versions/$versionId/content'
      preLoaderRoute: typeof V1SkillsSkillIdVersionsVersionIdContentRouteImport
      parentRoute: typeof V1SkillsSkillIdVersionsVersionIdRoute
    }
    '/v2/remote/hosts/$hostId/members/': {
      id: '/v2/remote/hosts/$hostId/members/'
      path: '/v2/remote/hosts/$hostId/members'
      fullPath: '/v2/remote/hosts/$hostId/members/'
      preLoaderRoute: typeof V2RemoteHostsHostIdMembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/remote/hosts/$hostId/members/$membershipId': {
      id: '/v2/remote/hosts/$hostId/members/$membershipId'
      path: '/v2/remote/hosts/$hostId/members/$membershipId'
      fullPath: '/v2/remote/hosts/$hostId/members/$membershipId'
      preLoaderRoute: typeof V2RemoteHostsHostIdMembersMembershipIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface V1MeRouteChildren {
  V1MeAvatarRoute: typeof V1MeAvatarRoute
  V1MeProfileRoute: typeof V1MeProfileRoute
}

const V1MeRouteChildren: V1MeRouteChildren = {
  V1MeAvatarRoute: V1MeAvatarRoute,
  V1MeProfileRoute: V1MeProfileRoute,
}

const V1MeRouteWithChildren = V1MeRoute._addFileChildren(V1MeRouteChildren)

interface V1MobileAuthDevicesRouteChildren {
  V1MobileAuthDevicesSessionIdRoute: typeof V1MobileAuthDevicesSessionIdRoute
}

const V1MobileAuthDevicesRouteChildren: V1MobileAuthDevicesRouteChildren = {
  V1MobileAuthDevicesSessionIdRoute: V1MobileAuthDevicesSessionIdRoute,
}

const V1MobileAuthDevicesRouteWithChildren =
  V1MobileAuthDevicesRoute._addFileChildren(V1MobileAuthDevicesRouteChildren)

interface V1SkillsSkillIdVersionsVersionIdRouteChildren {
  V1SkillsSkillIdVersionsVersionIdContentRoute: typeof V1SkillsSkillIdVersionsVersionIdContentRoute
}

const V1SkillsSkillIdVersionsVersionIdRouteChildren: V1SkillsSkillIdVersionsVersionIdRouteChildren =
  {
    V1SkillsSkillIdVersionsVersionIdContentRoute:
      V1SkillsSkillIdVersionsVersionIdContentRoute,
  }

const V1SkillsSkillIdVersionsVersionIdRouteWithChildren =
  V1SkillsSkillIdVersionsVersionIdRoute._addFileChildren(
    V1SkillsSkillIdVersionsVersionIdRouteChildren,
  )

interface V1SkillsSkillIdRouteChildren {
  V1SkillsSkillIdContentRoute: typeof V1SkillsSkillIdContentRoute
  V1SkillsSkillIdIconRoute: typeof V1SkillsSkillIdIconRoute
  V1SkillsSkillIdInstallRoute: typeof V1SkillsSkillIdInstallRoute
  V1SkillsSkillIdVersionsVersionIdRoute: typeof V1SkillsSkillIdVersionsVersionIdRouteWithChildren
}

const V1SkillsSkillIdRouteChildren: V1SkillsSkillIdRouteChildren = {
  V1SkillsSkillIdContentRoute: V1SkillsSkillIdContentRoute,
  V1SkillsSkillIdIconRoute: V1SkillsSkillIdIconRoute,
  V1SkillsSkillIdInstallRoute: V1SkillsSkillIdInstallRoute,
  V1SkillsSkillIdVersionsVersionIdRoute:
    V1SkillsSkillIdVersionsVersionIdRouteWithChildren,
}

const V1SkillsSkillIdRouteWithChildren = V1SkillsSkillIdRoute._addFileChildren(
  V1SkillsSkillIdRouteChildren,
)

interface V1MarketplaceAgentsAgentIdRouteChildren {
  V1MarketplaceAgentsAgentIdAvatarRoute: typeof V1MarketplaceAgentsAgentIdAvatarRoute
  V1MarketplaceAgentsAgentIdInstallRoute: typeof V1MarketplaceAgentsAgentIdInstallRoute
}

const V1MarketplaceAgentsAgentIdRouteChildren: V1MarketplaceAgentsAgentIdRouteChildren =
  {
    V1MarketplaceAgentsAgentIdAvatarRoute:
      V1MarketplaceAgentsAgentIdAvatarRoute,
    V1MarketplaceAgentsAgentIdInstallRoute:
      V1MarketplaceAgentsAgentIdInstallRoute,
  }

const V1MarketplaceAgentsAgentIdRouteWithChildren =
  V1MarketplaceAgentsAgentIdRoute._addFileChildren(
    V1MarketplaceAgentsAgentIdRouteChildren,
  )

interface V1SkillsAdminSubmissionsRouteChildren {
  V1SkillsAdminSubmissionsVersionIdRoute: typeof V1SkillsAdminSubmissionsVersionIdRoute
}

const V1SkillsAdminSubmissionsRouteChildren: V1SkillsAdminSubmissionsRouteChildren =
  {
    V1SkillsAdminSubmissionsVersionIdRoute:
      V1SkillsAdminSubmissionsVersionIdRoute,
  }

const V1SkillsAdminSubmissionsRouteWithChildren =
  V1SkillsAdminSubmissionsRoute._addFileChildren(
    V1SkillsAdminSubmissionsRouteChildren,
  )

interface V1MarketplaceAgentsAdminSubmissionsRouteChildren {
  V1MarketplaceAgentsAdminSubmissionsVersionIdRoute: typeof V1MarketplaceAgentsAdminSubmissionsVersionIdRoute
}

const V1MarketplaceAgentsAdminSubmissionsRouteChildren: V1MarketplaceAgentsAdminSubmissionsRouteChildren =
  {
    V1MarketplaceAgentsAdminSubmissionsVersionIdRoute:
      V1MarketplaceAgentsAdminSubmissionsVersionIdRoute,
  }

const V1MarketplaceAgentsAdminSubmissionsRouteWithChildren =
  V1MarketplaceAgentsAdminSubmissionsRoute._addFileChildren(
    V1MarketplaceAgentsAdminSubmissionsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppPreviewRoute: AppPreviewRoute,
  JoinRoute: JoinRoute,
  ReportSiteRoute: ReportSiteRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DotwellKnownAppleAppSiteAssociationRoute:
    DotwellKnownAppleAppSiteAssociationRoute,
  DotwellKnownJwksDotjsonRoute: DotwellKnownJwksDotjsonRoute,
  DownloadLinuxRoute: DownloadLinuxRoute,
  DownloadMacosRoute: DownloadMacosRoute,
  DownloadWindowsRoute: DownloadWindowsRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  GuidesRssDotxmlRoute: GuidesRssDotxmlRoute,
  HealthLiveRoute: HealthLiveRoute,
  HealthReadyRoute: HealthReadyRoute,
  NewsSlugRoute: NewsSlugRoute,
  NewsRssDotxmlRoute: NewsRssDotxmlRoute,
  PluginsSlugRoute: PluginsSlugRoute,
  V1MeRoute: V1MeRouteWithChildren,
  GuidesIndexRoute: GuidesIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  PluginsIndexRoute: PluginsIndexRoute,
  PluginsIconSlugRoute: PluginsIconSlugRoute,
  V1AuthLogoutRoute: V1AuthLogoutRoute,
  V1AvatarsUserIdRoute: V1AvatarsUserIdRoute,
  V1MobileAuthDevicesRoute: V1MobileAuthDevicesRouteWithChildren,
  V1MobileAuthRedeemRoute: V1MobileAuthRedeemRoute,
  V1MobileAuthSessionRoute: V1MobileAuthSessionRoute,
  V1MobileAuthTicketRoute: V1MobileAuthTicketRoute,
  V1SitesSiteIdRoute: V1SitesSiteIdRoute,
  V1SitesReportsRoute: V1SitesReportsRoute,
  V1SkillsSkillIdRoute: V1SkillsSkillIdRouteWithChildren,
  V1SkillsMineRoute: V1SkillsMineRoute,
  V1TeamAuthRedeemRoute: V1TeamAuthRedeemRoute,
  V1TeamAuthTicketRoute: V1TeamAuthTicketRoute,
  V1TeamHostsIceServersRoute: V1TeamHostsIceServersRoute,
  V1TeamInvitationsEmailRoute: V1TeamInvitationsEmailRoute,
  V1TeamTunnelsProvisionRoute: V1TeamTunnelsProvisionRoute,
  V1SitesIndexRoute: V1SitesIndexRoute,
  V1SkillsIndexRoute: V1SkillsIndexRoute,
  V1AuthEmailStartRoute: V1AuthEmailStartRoute,
  V1AuthEmailVerifyRoute: V1AuthEmailVerifyRoute,
  V1MarketplaceAgentsAgentIdRoute: V1MarketplaceAgentsAgentIdRouteWithChildren,
  V1MarketplaceAgentsMineRoute: V1MarketplaceAgentsMineRoute,
  V1SkillsAdminSubmissionsRoute: V1SkillsAdminSubmissionsRouteWithChildren,
  V2RemoteHostsRegisterRoute: V2RemoteHostsRegisterRoute,
  V2RemoteInvitesInviteIdRoute: V2RemoteInvitesInviteIdRoute,
  V2RemoteInvitesAcceptRoute: V2RemoteInvitesAcceptRoute,
  V2RemoteInvitesPreviewRoute: V2RemoteInvitesPreviewRoute,
  V2RemoteResumeValidateRoute: V2RemoteResumeValidateRoute,
  V1MarketplaceAgentsIndexRoute: V1MarketplaceAgentsIndexRoute,
  V2RemoteHostsIndexRoute: V2RemoteHostsIndexRoute,
  V2RemoteSessionsIndexRoute: V2RemoteSessionsIndexRoute,
  V1MarketplaceAgentsAdminSubmissionsRoute:
    V1MarketplaceAgentsAdminSubmissionsRouteWithChildren,
  V1SitesAdminSiteIdBlockRoute: V1SitesAdminSiteIdBlockRoute,
  V1SitesUploadsUploadIdActivateRoute: V1SitesUploadsUploadIdActivateRoute,
  V1SitesUploadsUploadIdFileRoute: V1SitesUploadsUploadIdFileRoute,
  V1SkillsAdminFeaturedSkillIdRoute: V1SkillsAdminFeaturedSkillIdRoute,
  V2RemoteHostsHostIdInvitesRoute: V2RemoteHostsHostIdInvitesRoute,
  V2RemoteHostsHostIdLogoRoute: V2RemoteHostsHostIdLogoRoute,
  V2RemoteHostsHostIdTicketRoute: V2RemoteHostsHostIdTicketRoute,
  V2RemoteSessionsSessionIdEndRoute: V2RemoteSessionsSessionIdEndRoute,
  V2RemoteSessionsSessionIdTicketRoute: V2RemoteSessionsSessionIdTicketRoute,
  V1MarketplaceAgentsAdminFeaturedAgentIdRoute:
    V1MarketplaceAgentsAdminFeaturedAgentIdRoute,
  V2RemoteHostsHostIdMembersMembershipIdRoute:
    V2RemoteHostsHostIdMembersMembershipIdRoute,
  V2RemoteHostsHostIdMembersIndexRoute: V2RemoteHostsHostIdMembersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
