import { execFileSync } from "node:child_process";
import { chmod, cp, mkdir, mkdtemp, readFile, rename, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { createDaniDexLogger } from "@dani-dex/logging";
import { z } from "zod";
import { type AgentRuntimeLock, loadAgentRuntimeLock } from "./agent-runtime-lock";
import { sha256 } from "./remote-desktop-runtime-release";

const logger = createDaniDexLogger("install-hermes-runtime");

export type HermesRuntimeTarget = "darwin-arm64" | "darwin-x64" | "linux-x64" | "win32-x64";

const HERMES_TARGETS: readonly HermesRuntimeTarget[] = ["darwin-arm64", "darwin-x64", "linux-x64", "win32-x64"];

const installedManifestSchema = z.object({
  layoutVersion: z.literal(1),
  version: z.string(),
  pythonVersion: z.string(),
  target: z.enum(["darwin-arm64", "darwin-x64", "linux-x64", "win32-x64"]),
  executable: z.enum(["bin/hermes", "bin/hermes.cmd"]),
  requirementsSha256: z.string(),
});

/**
 * The launchers resolve their own directory, so the tree still works after electron-builder copies
 * it into `Resources/hermes/<platform>/<arch>`. `-s` and `PYTHONNOUSERSITE` keep a user's own
 * `~/.local` packages out of the bundled interpreter, and the app bundle is read-only once signed,
 * so bytecode is compiled at build time instead of written beside the sources at run time.
 *
 * Windows gets a `.cmd`, not an `.exe`: the console-script executables pip and uv write hold an
 * absolute interpreter path into the build machine. `cliSpawnTarget` already runs a `.cmd` through
 * `cmd.exe` with verbatim arguments.
 */
const UNIX_LAUNCHER = `#!/bin/sh
# Dani-Dex bundled Hermes launcher. Generated by scripts/install-hermes-runtime.ts.
here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P) || exit 1
PYTHONNOUSERSITE=1 PYTHONDONTWRITEBYTECODE=1 exec "$here/../python/bin/python3" -s -m hermes_cli.main "$@"
`;

const WINDOWS_LAUNCHER = [
  "@echo off",
  "rem Dani-Dex bundled Hermes launcher. Generated by scripts/install-hermes-runtime.ts.",
  "setlocal",
  'set "PYTHONNOUSERSITE=1"',
  'set "PYTHONDONTWRITEBYTECODE=1"',
  '"%~dp0..\\python\\python.exe" -s -m hermes_cli.main %*',
  "",
].join("\r\n");

function isWindows(target: HermesRuntimeTarget): boolean {
  return target === "win32-x64";
}

function launcherName(target: HermesRuntimeTarget): "hermes" | "hermes.cmd" {
  return isWindows(target) ? "hermes.cmd" : "hermes";
}

function launcher(target: HermesRuntimeTarget): string {
  return isWindows(target) ? WINDOWS_LAUNCHER : UNIX_LAUNCHER;
}

function pythonExecutable(root: string, target: HermesRuntimeTarget): string {
  return isWindows(target) ? join(root, "python", "python.exe") : join(root, "python", "bin", "python3");
}

export async function installHermesRuntime(
  input: {
    sourceRoot?: string;
    outputRoot?: string;
    target?: HermesRuntimeTarget;
    fetchImpl?: typeof fetch;
    lock?: AgentRuntimeLock;
    uv?: string;
  } = {},
): Promise<"installed" | "current"> {
  const sourceRoot = input.sourceRoot ?? process.cwd();
  const outputRoot = input.outputRoot ?? resolve(sourceRoot, "build/hermes");
  const target = input.target ?? hermesRuntimeTarget();
  const fetchImpl = input.fetchImpl ?? fetch;
  const lock = input.lock ?? (await loadAgentRuntimeLock(sourceRoot));
  const uv = input.uv ?? process.env.UV ?? "uv";
  const hermes = lock.hermes;
  const artifact = hermes.python.artifacts[target];
  const targetRoot = hermesRuntimePath(outputRoot, target);
  const requirementsPath = resolve(sourceRoot, hermes.requirements);
  const requirements = await readFile(requirementsPath);
  verifyRequirements(requirements, lock);

  if (await isCurrentInstallation(targetRoot, target, lock)) {
    logger.info(`Using verified bundled Hermes ${hermes.version} for ${target}.`);
    return "current";
  }

  const url = `${hermes.python.repository}/releases/download/${hermes.python.release}/${encodeURIComponent(artifact.asset)}`;
  const archive = await download(fetchImpl, url, "Hermes Python runtime");
  if (sha256(archive) !== artifact.assetSha256) throw new Error(`The ${target} Hermes Python checksum is invalid.`);

  const temporaryRoot = await mkdtemp(join(tmpdir(), "dani-dex-hermes-install-"));
  try {
    const staged = join(temporaryRoot, "runtime");
    await mkdir(join(staged, "bin"), { recursive: true });
    const archivePath = join(temporaryRoot, artifact.asset);
    await writeFile(archivePath, archive);
    // The archive's single top-level directory is `python/`, which is the layout the launcher reads.
    execFileSync("tar", ["-xzf", archivePath, "-C", staged], { stdio: "inherit" });

    // `--target` with an explicit platform installs the wheels for the target, not the build host, so
    // one machine can stage every target. `--require-hashes` and `--only-binary` keep it to exactly
    // the locked wheels, and `--no-deps` stops anything the lock does not name.
    execFileSync(
      uv,
      [
        "pip",
        "install",
        "--require-hashes",
        "--no-deps",
        "--only-binary",
        ":all:",
        "--no-cache",
        "--python-version",
        hermes.python.version,
        "--python-platform",
        artifact.pythonPlatform,
        "--target",
        sitePackages(staged, target),
        "-r",
        requirementsPath,
      ],
      { stdio: "inherit" },
    );

    await writeFile(join(staged, "bin", launcherName(target)), launcher(target), {
      mode: isWindows(target) ? 0o644 : 0o755,
    });
    await writeFile(
      join(staged, "hermes-package.json"),
      `${JSON.stringify(
        {
          layoutVersion: 1,
          version: hermes.version,
          pythonVersion: hermes.python.version,
          target,
          executable: `bin/${launcherName(target)}`,
          requirementsSha256: hermes.requirementsSha256,
        },
        null,
        2,
      )}\n`,
    );
    if (target === hostTarget()) {
      // Only the host can run its own interpreter. Other targets are compiled when they are verified
      // on their own runner, which every release build does before packaging.
      execFileSync(pythonExecutable(staged, target), ["-m", "compileall", "-q", sitePackages(staged, target)], {
        stdio: "inherit",
      });
    }
    await verifyHermesRuntime(staged, target, lock);
    await installValidatedTree(staged, targetRoot);
    await verifyHermesRuntime(targetRoot, target, lock);
  } finally {
    await rm(temporaryRoot, { recursive: true, force: true });
  }

  await writeFile(
    join(outputRoot, "source-manifest.json"),
    `${JSON.stringify({ name: "hermes-agent", ...hermes }, null, 2)}\n`,
  );
  logger.info(`Installed bundled Hermes ${hermes.version} for ${target}.`);
  return "installed";
}

export function hermesRuntimeTarget(
  platform: string = process.platform,
  architecture: string = process.arch,
): HermesRuntimeTarget {
  const target = `${platform}-${architecture}`;
  const known = HERMES_TARGETS.find((candidate) => candidate === target);
  if (!known) throw new Error(`Unsupported bundled Hermes target: ${target}`);
  return known;
}

/** Matches `bundledHermesExecutable` in src/backend/hermes-cli.ts: `<platform>/<arch>/bin/hermes`. */
export function hermesRuntimePath(root: string, target: HermesRuntimeTarget): string {
  if (target === "darwin-arm64") return join(root, "mac", "arm64");
  if (target === "darwin-x64") return join(root, "mac", "x64");
  if (target === "win32-x64") return join(root, "win", "x64");
  return join(root, "linux", "x64");
}

export function verifyRequirements(requirements: Buffer, lock: AgentRuntimeLock): void {
  if (sha256(requirements) !== lock.hermes.requirementsSha256) {
    throw new Error("scripts/hermes-runtime-requirements.txt does not match the Hermes runtime lock.");
  }
  const text = requirements.toString("utf8");
  const pin = `${lock.hermes.package}==${lock.hermes.version} `;
  if (!text.includes(pin) || !text.includes(`--hash=sha256:${lock.hermes.wheelSha256}`)) {
    throw new Error("The Hermes requirements do not pin the locked hermes-agent wheel.");
  }
}

export async function verifyHermesRuntime(
  root: string,
  target: HermesRuntimeTarget,
  lock: AgentRuntimeLock,
): Promise<void> {
  const manifest = installedManifestSchema.parse(JSON.parse(await readFile(join(root, "hermes-package.json"), "utf8")));
  if (
    manifest.version !== lock.hermes.version ||
    manifest.pythonVersion !== lock.hermes.python.version ||
    manifest.target !== target ||
    manifest.executable !== `bin/${launcherName(target)}` ||
    manifest.requirementsSha256 !== lock.hermes.requirementsSha256
  ) {
    throw new Error("The bundled Hermes package manifest does not match the runtime lock.");
  }
  if ((await readFile(join(root, "bin", launcherName(target)), "utf8")) !== launcher(target)) {
    throw new Error("The bundled Hermes launcher is not the generated one.");
  }
  const license = await readFile(
    join(sitePackages(root, target), `hermes_agent-${lock.hermes.version}.dist-info`, "licenses", "LICENSE"),
    "utf8",
  );
  if (!license.startsWith("MIT License")) throw new Error("The bundled Hermes license is missing.");
  if (target !== hostTarget()) return;

  // The version goes through the interpreter the launcher runs, because Node cannot execute a `.cmd`
  // directly. The launcher itself is checked byte for byte above.
  const python = pythonExecutable(root, target);
  if (!isWindows(target)) await chmod(join(root, "bin", "hermes"), 0o755);
  const output = execFileSync(python, ["-s", "-m", "hermes_cli.main", "--version"], {
    encoding: "utf8",
    windowsHide: true,
    env: { ...process.env, PYTHONNOUSERSITE: "1", PYTHONDONTWRITEBYTECODE: "1" },
  }).trim();
  if (!new RegExp(`(?:^|\\s|v)${escapeRegExp(lock.hermes.version)}(?:\\s|$)`, "u").test(output)) {
    throw new Error(`Unexpected bundled Hermes version: ${output}`);
  }
  // `hermes acp` is what the driver spawns. Importing the adapter proves the `acp` extra landed
  // without starting a server that would wait on stdin.
  execFileSync(python, ["-s", "-c", "import acp, acp_adapter.entry"], { stdio: "inherit", windowsHide: true });
  if (!isWindows(target)) {
    // The real launcher, on the platforms where Node can run it.
    execFileSync(join(root, "bin", "hermes"), ["--version"], { encoding: "utf8" });
  }
}

function sitePackages(root: string, target: HermesRuntimeTarget): string {
  return isWindows(target)
    ? join(root, "python", "Lib", "site-packages")
    : join(root, "python", "lib", "python3.11", "site-packages");
}

function hostTarget(): HermesRuntimeTarget | null {
  try {
    return hermesRuntimeTarget();
  } catch {
    return null;
  }
}

async function download(fetchImpl: typeof fetch, url: string, label: string): Promise<Buffer> {
  const response = await fetchImpl(url, {
    headers: { "User-Agent": "Dani-Dex-runtime-installer" },
    redirect: "follow",
  });
  if (!response.ok) throw new Error(`${label} download failed with HTTP ${response.status}.`);
  return Buffer.from(await response.arrayBuffer());
}

async function isCurrentInstallation(
  root: string,
  target: HermesRuntimeTarget,
  lock: AgentRuntimeLock,
): Promise<boolean> {
  try {
    await verifyHermesRuntime(root, target, lock);
    return true;
  } catch {
    return false;
  }
}

async function installValidatedTree(source: string, destination: string): Promise<void> {
  const temporaryTarget = join(dirname(destination), `.${destination.split(/[\\/]/u).at(-1)}.installing`);
  await mkdir(dirname(destination), { recursive: true });
  await rm(temporaryTarget, { recursive: true, force: true });
  // `verbatimSymlinks`: the Python tree links `python3` to `python3.11`, and a resolved link would
  // point into the temporary directory that is deleted next.
  await cp(source, temporaryTarget, { recursive: true, verbatimSymlinks: true });
  await rm(destination, { recursive: true, force: true });
  await rename(temporaryTarget, destination);
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/gu, "\\$&");
}

if (import.meta.main) {
  await installHermesRuntime({
    target: hermesRuntimeTarget(process.argv[2] ?? process.platform, process.argv[3] ?? process.arch),
  });
}
